version: '3'

services:
  postgresql:
    image: postgres:12
    container_name: db_for_telegram
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    command: -p ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT}" ]
      interval: 5s
      timeout: 5s
      retries: 7
    restart: always

  rotate:
    build: .
    container_name: tg_parser
    entrypoint: ./docker-entrypoint.sh
    depends_on:
      postgresql:
        condition: service_healthy
    restart: always


volumes:
  postgres_data: